package app.lunch.model;

public enum Meal {
    FRIED_CHICKEN_WITH_YOGURT_SOUS,
    BAKED_FISH_WITH_VEGETABLES,
    BEAN_WITH_SALAD,
    BACKED_TURKEY_WITH_PATATOES,
    MEAT_BOLLS_WITH_TOMATOES_SOUS
    
}
